[env:esp8266]
platform = espressif8266
board = esp12e
framework = arduino
board_build.f_cpu = 160000000L
build_flags = -Isrc

lib_deps =
    adafruit/Adafruit ILI9341@^1.6.0
    adafruit/Adafruit GFX Library@^1.11.0
    paulstoffregen/XPT2046_Touchscreen
    knolleary/PubSubClient@^2.8
    tzapu/WiFiManager@^2.0.0
    bblanchon/ArduinoJson@^7.0.0
    tcmenu/TaskManagerIO@^1.5.0

