#!/usr/bin/env python3
"""Generate .clangd so clangd IntelliSense works with the xtensa toolchain.

The file contains machine-specific absolute paths, so it is gitignored and
(regenerated automatically on every PlatformIO build via extra_scripts, or
manually with:  python3 tools/gen_clangd.py
"""
import glob
import os
from pathlib import Path

TEMPLATE = """\
# AUTO-GENERATED by tools/gen_clangd.py — do not edit, do not commit.
#
# clangd config for the ESP8266 (xtensa-lx106) GCC toolchain.
#
# compile_commands.json (from `pio run -t compiledb`) contains xtensa-GCC
# flags that clang does not understand, and clang does not know the
# cross-compiler's built-in include paths.
CompileFlags:
  Remove:
    - -mlongcalls
    - -mtext-section-literals
    - -free
    - -fipa-pta

# SDK/toolchain headers contain xtensa-GCC extensions (inline asm register
# constraints, void* arithmetic, ELF section attributes) that stock clang
# cannot parse. Suppress diagnostics from those headers only — project
# sources under src/ are checked normally.
Diagnostics:
  Includes:
    IgnoreHeader:
      - ".*/.platformio/packages/.*"
      - ".*/.pio/libdeps/.*"
  Suppress:
    - attribute_section_invalid_for_target

---
# Firmware sources only: keep the xtensa flags away from native unit tests
# (test/.clangd), which are compiled with the host toolchain and need the
# host C++ library (gtest requires <mutex>, missing in xtensa libstdc++).
If:
  # PathMatch is evaluated against the file path RELATIVE to this config
  PathMatch: "src[/].*"
CompileFlags:
  Add:
    # Don't mix the host macOS libc++ with the xtensa libstdc++ below
    - -nostdinc++
    # newlib's sys/unistd.h uses `__block` as a parameter *name*; clang on
    # the macOS host target treats it as the Blocks keyword. Disable blocks.
    - -fno-blocks
    # SDK headers still emit (ignored) xtensa-asm diagnostics; don't let
    # them abort the parse early.
    - -ferror-limit=0
    # Order matters: must mirror GCC's search order (C++ dirs FIRST), so
    # that libstdc++'s #include_next <stdlib.h> resolves to newlib instead
    # of the macOS SDK.
{isystem}
"""


def find_toolchain():
    candidates = [
        Path(os.path.expanduser("~/.platformio/packages/toolchain-xtensa")),
        Path(os.environ.get("PLATFORMIO_CORE_DIR", "")) / "packages/toolchain-xtensa",
    ]
    for pkg in candidates:
        cxx = sorted(glob.glob(str(pkg / "xtensa-lx106-elf/include/c++/*")))  # e.g. 10.3.0
        gcc = sorted(glob.glob(str(pkg / "lib/gcc/xtensa-lx106-elf/*/include")))
        newlib = pkg / "xtensa-lx106-elf/include"
        if cxx and gcc and newlib.is_dir():
            return [
                cxx[-1],
                f"{cxx[-1]}/xtensa-lx106-elf",
                gcc[-1],
                str(newlib),
            ]
    return None


def main():
    project_dir = Path(os.environ.get("PLATFORMIO_PROJECT_DIR", ".")).resolve()
    paths = find_toolchain()
    if not paths:
        print("gen_clangd: toolchain-xtensa not found; keeping existing .clangd")
        return
    isystem = "\n".join(f"    - -isystem\n    - {p}" for p in paths)
    out = project_dir / ".clangd"
    out.write_text(TEMPLATE.format(isystem=isystem))
    print(f"gen_clangd: wrote {out}")


try:
    Import("env")  # noqa: F821  (present when run as a PlatformIO extra script)
    os.environ.setdefault("PLATFORMIO_PROJECT_DIR", env.subst("$PROJECT_DIR"))  # noqa: F821
except Exception:
    pass

main()
